<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220807075300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'ACHERES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'AHUY MUREE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'AIX - LE SULKY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'AIX LE SULKY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'ALTICE CAMPUS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'AMIENS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'ANGLET CANAL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'ANGOULEME')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'AYTRÉ')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BASTIA')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BAYONNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BEAUVAIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BEAUVAIS - BEAUVAISIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BOL SFR-BT CONQUETE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BORDEAUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BORDEAUX - MERIGNAC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BORDEAUX KENNEDY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BORDEAUX LAC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BORDEAUX MERIGNAC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BORDEAUX VILLENAVE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BORDEAUX-VILLENAVE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BOURG EN BRESSE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BOURG-EN-BRESSE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BOUTIQUE PP CAEN AVENUE DU 6 JUIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BREST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BREST GUIPAVAS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ ANGERS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ ANGOULEME RUE RENE GOSCINNY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ ANNECY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ ANTIBES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ AVIGNON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ BASTIA')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ BAYONNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ BORDEAUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ CAVAILLON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ CHAMPS SUR MARNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ CLERMONT FERRAND')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ DIJON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ DUNKERQUE CENTRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ GRENOBLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ LE MANS RUE DE L'ETOILE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ LILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ LIMOGES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ LYON CREQUI')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ MARSEILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ MARSEILLE LE MERLAN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ METZ')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ MONTPELLIER')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ MULHOUSE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ NANCY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ NICE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ NIMES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ PARIS AVENUE DES TERNES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ PARIS RUE DE PASSY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ PTN PREM BESANCON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ PTN PREM MONTPELLIER GRAND RUE JEAN MOULI')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ REIMS RUE DE VESLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ RENNES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ ROUEN RUE GUILLAUME LE CONQUERANT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ THOIRY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ TOULOUSE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ TOURS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ TOURS RUE DE BORDEAUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'BTQ VALENCE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'CAMPUS SAINT-DENIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'CE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'CHAMPS SUR MARNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'CHARTRES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'CLERMONT FERRAND AUBIERE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'CLERMONT-FERRAND - AUBIERE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'COURBEVOIE PROLOGUE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'COVERCOM ENTREPRISES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'DIJON AHUY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'EXTERIEUR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'FACILYT'K')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'GENTILLY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'GRENOBLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'GRENOBLE - ETOILE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'GRENOBLE - INOVATEL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'GRENOBLE - MONTBONNOT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'GRENOBLE - ST MARTIN HERES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'GRENOBLE ETOILE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'HEROUVILLE-SAINT-CLAIR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'ICART ROUEN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'IDF')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'ISNEAUVILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - CARREFOUR STE-CLOTILDE 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - CARREFOUR STE-SUZANNE 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - FRONT DE MER')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - KERVEGUEN 1')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - KERVEGUEN 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - KERVEGUEN 3')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - LE CHAUDRON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - LE PORT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - LE PORT II')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - LE TAMPON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - LES  MANGUIERS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - MARECHAL LECLERC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - SAINT JOSEPH')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - SAINT LOUIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - SAINT-GILLES 3')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - SAINT-LEU 3')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - SAINT-PAUL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA REUNION - SAINT-PIERRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LA ROCHELLE AYTRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LAMPERTHEIM')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LE HAVRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LE MANS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LE MANS -ARNAGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LE MANS ARNAGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LE MANS TDR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LES ULIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LIEVIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LILLE - CASTEL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LILLE - REPUBLIQUE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LILLE CASTEL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LILLE WASQUEHAL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LIMONEST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LTI AIX EN PROVENCE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LTI DARDILLY (LYON)')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LTI LIMONEST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LTI NANTES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LYON - BRON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LYON - DECINES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LYON - PAUL SEDALLIAN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LYON - SAINT-PRIEST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LYON - VENISSIEUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LYON BRON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LYON DECINES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LYON PAUL SEDALLIAN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LYON SAINT PRIEST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'LYON SAINT PRIEST 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MARSEILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MARSEILLE - L'ESTAQUE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MARSEILLE - LA VALENTINE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MAYOTTE - BAOBAB')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MAYOTTE - COMBANI')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MAYOTTE - DZOUMOGNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MAYOTTE - JUMBO')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MAYOTTE - KAWENI2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MAYOTTE - PETITE TERRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MAYOTTE - PLACE MARIAGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MAYOTTE - RUE DU COMMERCE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MEDITERRANEE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'METZ')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'METZ - ARAGO')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'METZ ARAGO')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MEUDON 1')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MEUDON 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MONTPELLIER')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MONTPELLIER SFR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MULHOUSE MER ROUGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'MULHOUSE SAUSHEIM')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NANTERRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NANTES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NANTES - SAINT-HERBLAIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NANTES SAINT HERBLAIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NICE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NICE - ANTIPOLIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NICE - LA PLAINE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NICE LA PLAINE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NIMES (AGENCE)')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NIMES - CAISSARGUES (PLATEAU)')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NIMES AGENCE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NIMES CAISSARGUES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NIORT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NORD EST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'NORD NORMANDIE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'ORLEANS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'ORLEANS - SARAN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'ORLEANS SARAN MSC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'OUEST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PALAISEAU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PALAISEAU COLUMBIA')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PALAISEAU COLUMBIA TDR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PARIS - BELA BARTOK')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PARIS - GENTILLY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PARIS - ISSY-LES-MOULINEAUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PARIS - LES ULIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PARIS BELA BARTOK')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PARIS COURBEVOIE - LE PROLOGUE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PARIS MASSY - LE CAMPUS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PARIS NANTERRE - RIVE DEFENSE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PAU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'PERIGUEUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'REIMS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'REIMS - VERNOUILLET')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'REIMS VERNOUILLET TDR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'RENNES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'RENNES - CHANTEPIE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'RENNES - VERN SUR SEICHE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'RIVESALTES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SAINT ETIENNE LA FOUILLOUSE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SAINT- LO')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SAINT-ETIENNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SAINT-HERBLAIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR BUSINESS SOLUTION - BORDEAUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR BUSINESS SOLUTION - LES ULIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR BUSINESS SOLUTION - LILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR BUSINESS SOLUTION - LYON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR BUSINESS SOLUTION - MAROC CASABLANCA')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR BUSINESS SOLUTION - MARSEILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR BUSINESS SOLUTION - RENNES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR BUSINESS SOLUTION - STRASBOURG')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR BUSINESS SOLUTION - TOULOUSE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP  BORDEAUX MERIADECK')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP  EPINAL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP  POISSONNIERE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP  RIVOLI')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP AGEN REPUBLIQUE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP AIX EN PROVENCE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP AIX EN PROVENCE MIRABEAU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ALBERTVILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ALBI LE SEQUESTRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ALLONNES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP AMIENS 31-3 CAILLOUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP AMIENS GLISY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ANGERS ALSACE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ANGERS ANJOU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ANGERS GRAND MAINE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ANGERS LENEPVEU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ANGERS ST AUBIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ANGERS ST SERGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ANGOULEME')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ANGOULEME CHAMPNIERS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ANNECY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ANNEMASSE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ANTIBES GRASSE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ARCONNAY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ARCUEIL VACHE NOIRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ARGENTEUIL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ARLES LICES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP AUBAGNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP AUBIERE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP AUTEUIL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP AVIGNON LE PONTET')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP AVIGNON MISTRAL 7')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP AVRANCHES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BAB 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BAGNOLET BEL EST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BARJOUVILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BAYEUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BAYONNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BEAUVAIS CARNOT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BEAUVAIS DESCARTES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BELFORT FBG DE FRANCE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BERCK')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BESANCON CHATEAUFARINE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BESANCON GDE RUE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BETHUNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BEZIER GEANT II')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BEZIERS AUCHAN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BEZIERS HOURS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BEZIERS PAUL RIQUET')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BIARRITZ')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BIGANOS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BLAGNAC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BONNEVEINE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BORDEAUX BEGLES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BORDEAUX DIJEAUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BORDEAUX ESR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BORDEAUX LAC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BORDEAUX ST EULALIE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BORDEAUX ST MEDARD')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BOURG EN BRESSE 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BOURG LES VALENCE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BOURGES COMMERCE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BREST IROISE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BREST SIAM')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BRETIGNY SUR ORGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BRIVE KOENING CENTRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP BRIVE RIVET OUEST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CAEN HEROUVILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CAEN MONDEVILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CAEN STRASBOURG')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CALAIS 4 BOULEVARDS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CANNES 5 ANTIBES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CARRE SENART')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CERGY 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHALEZEULE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHALON S/SAONE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHALONS EN CHAMPAGNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHALONS LOMBARDS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHAMBERY CHAMNORD')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHAMBERY GENEVE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHAMPS ELYSEES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHARLEVILLE MEZIERES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHARTRES NOEL BALLAY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHAUMONT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHAUSSEE D'ANTIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHELLES 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHERBOURG GLACERIE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CHERBOURG PORTES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CLAIRA')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CLAYE SOUILLY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CLERMONT-FERRAND 11 NOVEMBRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CLUSES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP COGNAC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CRETEIL BAS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP CRETEIL SOLEIL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP DARDILLY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP DENAIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP DIEPPE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP DIEPPE GDE RUE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP DIJON CHENOVE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP DIJON QUETIGNY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP DIJON TOISON D'OR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP DOLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP DRAGUIGNAN CISSON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP DRANCY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP DREUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ECHIROLLES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ECULLY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ELBEUF')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ENGLOS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP EPAGNY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP EPERNAY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP EPINAL MINIMES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP EVREUX CHARTRAINE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP EVRY 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP FACHES THUMESNIL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP FAUBOURG ST ANTOINE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP FENOUILLET')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP FLINS SUR SEINE 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP FONTENAY-SOUS-BOIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP FORUM')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP FREJUS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP GIEN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP GIVORS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP GRAND PLAISIR 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP GRANDE SYNTHE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP GRENOBLE GRAND PLACE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP GRENOBLE SAULT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP GRUCHET')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP HOUDEMONT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP HYERES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ISTRES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ITALIE 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP L AIGLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP L' ISLE D'ADAM')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP L'ISLE D'ABEAU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LA DEFENSE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LA GARDE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LA MAYENNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LA ROCHELLE ANGOULINS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LA ROCHELLE TEMPLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LA SEYNE SUR MER')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LA VALENTINE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LANESTER')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LE HAVRE GONFREVILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LE HAVRE GRAND CAP')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LE HAVRE HOTEL DE VILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LE MANS CENTRE SUD')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LE MANS DR LEROY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LE MANS MARCHANDE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LE MANS ST AUBIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LEERS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LEMPDES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LENS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LENS JAURES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LES ANGLES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LESCAR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LIBOURNE 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LILLE EURALILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LILLE RUE NEUVE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LILLE WASQUEHAL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LIMOGES BOISSEUIL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LIMOGES COUPOLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LIMOGES ST MARTIAL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LISIEUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LOMME')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LORIENT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LORMONT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LOUVROIL MAUBEUGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LUNEL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LYON BELLECOUR ESR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LYON LA PART DIEU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP LYON OXYGENE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MACON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MAISONS-LAFFITTE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MALEMORT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MANOSQUE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MANTES LA JOLIE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MARSEILLE AVANT CAP')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MARSEILLE CANEBIERE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MARSEILLE CC VALENTINE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MARSEILLE GRAND LITTORAL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MARSEILLE PRADO')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MARTIGUES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MARZY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MASSY EUROPE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MENTON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MERIGNAC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP METZ')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP METZ PUHL DEMANGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MOISSELLES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MONT DE MARSAN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MONTARGIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MONTCEAU LES MINES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MONTESSON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MONTIVILLIERS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MONTPELLIER LA LOGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MONTPELLIER LATTES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MONTPELLIER PEROLS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MONTPELLIER POLYGONE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MONTREUIL GRANDE PORTE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MORLAIX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MULHOUSE ILLZACH')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MULHOUSE MERCIERE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP MURET')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NANCY ST SEBASTIEN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NANTERRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NANTES BEAULIEU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NANTES ESR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NANTES PARIDIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NANTES REZE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NANTES SEBASTIEN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NARBONNE BONNE SOURCE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NARBONNE PONT DES MARCHANDS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NEMOURS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NEUILLY PLAISANCE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NICE ETOILE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NICE LINGOSTIERE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NICE TNL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NICE TRINITE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NIMES COSTIERES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NIMES ETOILE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NIORT CHAURAY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NOGENT LE ROTROU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NOISY ARCADES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP NOYELLES GODAULT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP OLLIOULES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ORANGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ORLEANS CHECY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ORLEANS SARAN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ORMESSON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP OSNY LACROIX ST SIMON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP OYONNAX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PAMIERS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PARINOR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PARIS G. LECLERC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PARIS MASSENA')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PARIS NATION')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PARIS OPERA')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PARIS PASSY II')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PARIS SEBASTOPOL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PARIS SECRETAN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PARLY 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PAU LESCAR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PAU PYRENEES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PERIGUEUX BUGEAUD')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PERPIGNAN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PERPIGNAN P. ESPAGNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PHONE SHOP CHAMBRAY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PHONE SHOP LIEVIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PHONE SHOP TORCY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PITHIVIERS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PLAN DE CAMPAGNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP POISSY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP POITIERS BEAULIEU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PONTARLIER')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PONTAULT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PORNIC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PORTET S/ GARONNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PUGET SUR ARGENS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP PUILBOREAU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP QUAI D'IVRY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP QUIMPER CORENTIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP QUIMPER CORNOUAILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP RAMBOUILLET')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP REDON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP REIMS CORMONTREUIL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP REIMS ST BRICE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP REIMS TALLEYRAND')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP REMIREMONT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP RENNES  PACE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP RENNES ALMA')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP RENNES CESSON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP RENNES LONGS CHAMPS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP RENNES ST GREGOIRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP REPUBLIQUE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ROANNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ROCHEFORT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ROISSY AEROVILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ROMANS SUR ISERE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ROMORANTIN LANTHENAY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ROQUES /GARONNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ROSNY S/BOIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ROUEN 33 GROS HORLOGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ROUEN BARENTIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ROUEN ST AIGNAN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ROUEN TOURVILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SAINT AVOLD')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SAINT GENIS LAVAL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SAINT HERBLAIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SAINT MAXIMIN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SAINT NAZAIRE TRIGNAC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SAINT ORENS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SAINT QUENTIN LE FAYET')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SAINT-BRICE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SAINTES MARECHAL LECLERC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SALLANCHES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SARCELLES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SARTROUVILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SEMECOURT 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SETE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP SIN LE NOBLE  II')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST ANDRE DE CUBZAC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST BRIEUC ST GUILLAUME')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST CLEMENT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST ETIENNE FOY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST ETIENNE MONTHIEU')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST ETIENNE VILLARS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST JEAN DE LA RUELLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST JEAN DE VEDAS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST LAURENT DU VAR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST LAZARE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST LO')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST NAZAIRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST PAUL LES DAX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST PRIEST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST QUENTIN EN YVELINES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST RAPHAEL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST SULPICE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP ST-BRIEUC/LANGUEUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP STE GENEVIEVE CROIX BLANCHE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP STE MARIE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP STRASBOURG ILLKRICH')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP STRASBOURG MUNDO')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TAVERNY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TERNES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP THIAIS BELLE EPINE 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP THIONVILLE  GERIC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP THONON LES BAINS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TOULON GRAND VAR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TOULOUSE ESR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TOULOUSE GRAMONT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TOULOUSE LABEGE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TOULOUSE LAFAYETTE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TOURS 47 NATIONALE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TOURS BORDEAUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TOURS L HEURE TRANQUILLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TOURS LES ATLANTES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TOURS PETITE ARCHE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP TROYES LA CHAPELLE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VAL D'EUROPE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VAL D'YERRES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VAL THOIRY II')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VALDOLY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VALENCE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VALENCIENNES PETITE FORET')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VAULX EN VELIN 2')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VELIZY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VENDOME')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VERDUN')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VERNON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VERNOUILLET')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VESOUL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VICTOR HUGO II')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VIENNE ROMESTANG')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VILLEBON SUR YVETTE CC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VILLENEUVE D'ASCQ')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VILLENEUVE LA GARENNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VILLENEUVE SUR LOT')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VILLEURBANNE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VILLIERS EN BIERE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VINEUIL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VIRE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VIRY CHATILLON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VITROLLES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP VOIRON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SFR ESP WITTENHEIM')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SITE EXTERIEUR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SONDE SUIVI PANORAMA')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SONDES PRICE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'STRASBOURG')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'STRASBOURG (NETCENTER)')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'STRASBOURG - ENTZHEIM')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'STRASBOURG - RUE DE COLMAR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'STRASBOURG NETCENTER')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'STRASBOURG RUE DE COLMAR')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SUD OUEST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'SURESNES')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'TELECOM COMMUNICATION INFORMATIQUE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'TELEVENTE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'TELEVENTE WHP CENTRE EST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'TELEVENTE WHP IDF')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'TOULON')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'TOULOUSE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'TOULOUSE - BASSO CAMBO')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'TOULOUSE BASSO CAMBO')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'TOURS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'VAISE')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'VAL DE REUIL')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'VELIZY')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, 'VILLENEUVE LOUBET')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, '[FUTUR] BORDEAUX')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, '[FUTUR] LIMONEST')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, '[FUTUR] MÉRIGNAC')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, '[FUTUR] PARIS')");
        $this->addSql("INSERT INTO sfadb.local_branch(created_at, name) VALUES(current_timestamp, '[FUTUR] SAINT HERBLAIN')");
    }

    public function down(Schema $schema): void
    {
    }
}
